#!/usr/bin/env ruby

site 'http://community.opscode.com/api/v1'

cookbook 'apache2', '1.8.14'
cookbook 'apt', '2.3.0'
cookbook 'postgresql', '3.3.4'
cookbook 'rabbitmq', '2.3.2'
cookbook 'icecast2', '0.0.1'
cookbook 'ubuntu', '1.1.2'
cookbook 'database', '1.5.2'
cookbook "phauneradio",
  :github => "Freq-Out/chef-phauneradio",
  :ref => "v0.1.0"
cookbook "airtime",
  :github => "Freq-Out/chef-airtime",
  :ref => "v0.1.1"
 
